version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hypertube
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /goinfre/kfaouzi/42/hypertube/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - hypertube-network
    

volumes:
  postgres_data:

networks:
  hypertube-network: