version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hypertube
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "http", "http://localhost:8000/health/check/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - hypertube-network
    volumes:
      - .:/app

  database:
    container_name: database
    image: postgres:14
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - hypertube-network

volumes:
  postgres_data:

networks:
  hypertube-network:
    name: hypertube-network
    driver: bridge